version: '3.1'

services:
  db:
    container_name: db-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - $DB_PORT:5432
