app = "surveyform"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"
  APP_ENV = "production"
  DB_CONNECTION = "mysql"
  MYSQL_ATTR_SSL_CA = "/etc/ssl/certs/ca-certificates.crt"
  DB_HOST = "127.0.0.1"
  DB_PORT = "3306"
  DB_USERNAME = "root"
  DB_PASSWORD = "root"
  DB_NAME = "google_form_db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "new_volume"
  destination = "/path/in/app"
